name: Deploy Staking Vault

on:
 push:
    branches: [main]

jobs:
    build-and-deploy:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout repo
           uses: actions/checkout@v3

         - name: Setup Node
           uses: actions/setup-node@v3
           with:
             node-version: 20

         - name: Install Dependencies
           run: npm install --force

         - name: Compile Contract
           run: npx hardhat compile

         - name: Test
           run: npx hardhat test